-- Script para criar as tabelas TBL_INM_* no SQLite
-- Estrutura ATUALIZADA com todas as colunas corrigidas
-- Baseado na estrutura do PostgreSQL e nas referências do código
-- Adaptado para SQLite com todas as funcionalidades de Parto Adequado

-- Tabela principal de atendimento
CREATE TABLE "TBL_INM_ATENDIMENTO" (
    "SITUACAO_INTERNACAO" INTEGER,
    "CARATER_INTERNACAO" INTEGER,
    "PROCEDENCIA_PACIENTE" TEXT,
    "LEITO" TEXT,
    "NR_OPERADORA_FONTE_PAGADORA" TEXT,
    "NR_REGISTRO" TEXT,
    "NR_ATENDIMENTO" INTEGER,
    "NR_AUTORIZACAO" INTEGER,
    "DT_INTERNACAO" DATETIME,
    "DT_ALTA" DATETIME,
    "CONDICAO_ALTA" TEXT,
    "DT_AUTORIZACAO" DATETIME,
    "CD_CID_PRINCIPAL" TEXT,
    "PACIENTE_INTERNADO_OUTRAS_VEZES" TEXT,
    "HOSPITAL_INTERNACAO_ANTERIOR" TEXT,
    "ULTIMA_INTERNACAO_30_DIAS" TEXT,
    "INTERNACAO_COMPLICACAO_RECAIDA" TEXT,
    "ACAO" TEXT,
    "NENHUM_DISPOSITIVO_TERAPEUTICO" TEXT,
    "NOTA" TEXT,
    "TIPO_NOTA" TEXT,
    "DT_NOTA" DATETIME,
    "CD_HOSPITAL" INTEGER,
    "NM_HOSPITAL" TEXT,
    "CNES_HOSPITAL" INTEGER,
    "PORTE_HOSPITAL" INTEGER,
    "COMPLEXIDADE_HOSPITAL" INTEGER,
    "ESFERA_ADM_HOSPITAL" INTEGER,
    "UF_HOSPITAL" TEXT,
    "CIDADE_HOSPITAL" TEXT,
    "CODIGO_MUNICIPIO_HOSPITAL" TEXT,     -- Código do município (12 chars numérico)
    "TP_LOGRADOURO_HOSPITAL" TEXT,
    "LOGRADOURO_HOSPITAL" TEXT,
    "NR_LOGRADOURO_HOSPITAL" INTEGER,
    "COMPLEMENTO_LOGRADOURO_HOSPITAL" TEXT,
    "BAIRRO_HOSPITAL" TEXT,
    "CEP_HOSPITAL" TEXT,
    "DT_NASC_PAC" DATETIME,
    "SEXO_PAC" TEXT,
    "CPF_PAC" TEXT,
    "CNS_PAC" TEXT,
    "CODIGO_IDENTIFICACAO" TEXT,         -- Código ID do beneficiário (15 chars)
    "RECEM_NASCIDO_PAC" TEXT,
    "PARTICULAR_PAC" TEXT,
    "VULNERABILIDADE_SOCIAL_PAC" TEXT,
    "UF_PAC" TEXT,
    "CIDADE_PAC" TEXT,
    "CODIGO_MUNICIPIO_PAC" TEXT,         -- Código do município do paciente (12 chars numérico)
    "TP_LOGRADOURO_PAC" TEXT,
    "LOGRADOURO_PAC" TEXT,
    "NR_LOGRADOURO_PAC" TEXT,
    "COMPLEMENTO_LOGRADOURO_PAC" TEXT,
    "BAIRRO_PAC" TEXT,
    "CEP_PAC" TEXT,
    "CD_OPERADORA" TEXT,
    "PLANO_OPERADORA" TEXT,
    "NR_CARTEIRA" TEXT,
    "DT_VALIDADE_OPERADORA" DATETIME,
    "TP_SUP_VENT" TEXT,
    "LOCAL_SUP_VENT" TEXT,
    "TP_INVASIVO_SUP_VENT" TEXT,
    "DT_INICIAL_SUP_VENT" DATETIME,
    "DT_FINAL_SUP_VENT" TEXT,
    "CD_CONDICAO_ADQUIRIDA" TEXT,
    "DT_OCORRENCIA_SUP" TEXT,
    "NR_ATEND_ALTA_ADM" TEXT,
    "NR_AUTORIZACAO_ALTA_ADM" TEXT,
    "CESARIANA_PARTO_ADEQUADO" TEXT,
    "MEDICACAO_INDUCAO_PARTO" TEXT,
    "NR_PARTOS_ANTERIORES" TEXT,
    -- Campos completos de Parto Adequado conforme DRG
    "ANTECEDENTES_OBSTETRICOS" TEXT,
    "NUMERO_CESAREAS_ANTERIORES" TEXT,
    "APRESENTACAO_FETAL_RN1" TEXT,
    "APRESENTACAO_FETAL_RN2" TEXT,
    "APRESENTACAO_FETAL_RN3" TEXT,
    "APRESENTACAO_FETAL_RN4" TEXT,
    "APRESENTACAO_FETAL_RN5" TEXT,
    "INICIO_TRABALHO_PARTO" TEXT,
    "RUPTURA_UTERINA" TEXT,
    "LACERACAO_PERINEAL" TEXT,
    "TRANSFUSAO_SANGUINEA" TEXT,
    "MORTE_MATERNA" TEXT,
    "MORTE_FETAL_INTRAPARTO" TEXT,
    "ADMISSAO_MATERNA_UTI" TEXT,
    "RETORNO_SALA_PARTO" TEXT,
    "INDICE_SATISFACAO_HOSPITAL" TEXT,
    "INDICE_SATISFACAO_EQUIPE" TEXT,
    "HOUVE_CONTATO_PELE" TEXT,
    "POSICAO_PARTO" TEXT,
    "USO_OCITOCINA_MISOPROSTOL" TEXT,
    "PARTURIENTE_ACOMPANHADA" TEXT,
    "PRESENCA_DOULA" TEXT,
    "REALIZADA_EPISIOTOMIA" TEXT,
    "HOUVE_ALEITAMENTO_MATERNO" TEXT,
    "QUANDO_OCORREU_CLAMPAMENTO" TEXT,
    "HOUVE_METODOS_ANALGESIA" TEXT,
    "METODO_ANALGESIA" TEXT,
    "PERIMETRO_CEFALICO_RN1" TEXT,
    "PERIMETRO_CEFALICO_RN2" TEXT,
    "PERIMETRO_CEFALICO_RN3" TEXT,
    "PERIMETRO_CEFALICO_RN4" TEXT,
    "PERIMETRO_CEFALICO_RN5" TEXT,
    "TP_STATUS" TEXT,
    "CD_ESTABELECIMENTO" TEXT,
    "DS_ERRO" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER PRIMARY KEY AUTOINCREMENT
);

-- Tabela de médicos
CREATE TABLE "TBL_INM_MEDICO" (
    "NM_MEDICO" TEXT,
    "DDD_MEDICO" INTEGER,
    "NR_TELEFONE_MEDICO" INTEGER,
    "EMAIL_MEDICO" TEXT,
    "UF_MEDICO" TEXT,
    "CRM_MEDICO" TEXT,
    "ESPECIALIDADE_MEDICO" TEXT,
    "MEDICO_RESPONSAVEL" TEXT,
    "TP_ATUACAO_MEDICO" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de CID secundário
CREATE TABLE "TBL_INM_CID_SEC" (
    "CD_CID" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de procedimentos
CREATE TABLE "TBL_INM_PROCEDIMENTO" (
    "CD_PROCEDIMENTO" TEXT,
    "DT_EXEC" DATETIME,
    "DT_SOLIC" DATETIME,
    "DT_FIM_EXEC" DATETIME,
    "CD_CIRURGIA_AVISO" TEXT,
    "CRM_MEDICO_PROCEDIMENTO" TEXT,
    "UF_MEDICO_PROCEDIMENTO" TEXT,
    "TP_ATUACAO_MEDICO_PROCEDIMENTO" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de CTI
CREATE TABLE "TBL_INM_CTI" (
    "LEITO_CTI" TEXT,
    "DT_INICIAL_CTI" DATETIME,
    "DT_FINAL_CTI" DATETIME,
    "CD_CID_PRINCIPAL" TEXT,
    "CONDICAO_ALTA_CTI" TEXT,
    "UF_CTI" TEXT,
    "CRM_CTI" TEXT,
    "CD_HOSPITAL" TEXT,
    "NM_HOSPITAL" TEXT,
    "DS_LEITO" TEXT,
    "TIPO" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de suporte ventilatório
CREATE TABLE "TBL_INM_SUPORTEVENTILATORIO" (
    "TP_SUP_VENT" TEXT,
    "LOCAL_SUP_VENT" TEXT,
    "TP_INVASIVO_SUP_VENT" TEXT,
    "DT_INICIAL_SUP_VENT" DATETIME,
    "DT_FINAL_SUP_VENT" TEXT,
    "DT_INICIAL_SUP_VENTILATORIO" DATETIME,
    "DT_FINAL_SUP_VENTILATORIO" DATETIME,
    "CD_CID_COND_ADQ_VENT" TEXT,
    "DT_COND_ADQ_VENT" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de cateter vascular central
CREATE TABLE "TBL_INM_CATETERVASCULARCENTRAL" (
    "LOCAL_CAT_VAS" TEXT,
    "DT_INICIO_CAT_VAS" TEXT,
    "DT_FIM_CAT_VAS" TEXT,
    "CD_CID_CAT_VAS" TEXT,
    "DT_CAT_VAS" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de sonda vesical de demora
CREATE TABLE "TBL_INM_SONDAVESICALDEDEMORA" (
    "LOCAL_SON_VES" TEXT,
    "DT_INICIO_SON_VES" TEXT,
    "DT_FIM_SON_VES" TEXT,
    "CD_CID_COND_ADQ_SONDA" TEXT,
    "DT_COND_ADQ_SONDA" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de condição adquirida
CREATE TABLE "TBL_INM_COND_ADQ" (
    "CD_CID_COND_ADQ" TEXT,
    "DT_OCORRENCIA_COND_ADQ" TEXT,
    "DT_MANIFESTACAO_COND_ADQ" TEXT,
    "UF_MED_COND_ADQ" TEXT,
    "CRM_MED_COND_ADQ" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Recém-Nascido (RN)
CREATE TABLE "TBL_INM_RN" (
    "PESO_NASCIMENTO" INTEGER,           -- Peso em gramas
    "IDADE_GESTACIONAL" TEXT,            -- Em semanas (99.9)
    "COMPRIMENTO" TEXT,                  -- Em cm (99.9)
    "SEXO_RN" TEXT,                      -- M/F/I
    "NASCIDO_VIVO" TEXT,                 -- S/N
    "TOCOTRAUMATISMO" TEXT,              -- S/N/I
    "APGAR" TEXT,                        -- S/N/I
    "APGAR_QUINTO_MINUTO" INTEGER,       -- 0-10
    "ALTA_48_HORAS" TEXT,                -- S/N
    "NR_AUTORIZACAO_MAE" TEXT,           -- 25 chars
    "NR_ATENDIMENTO_MAE" TEXT,           -- 25 chars
    "NR_CARTEIRA_MAE" TEXT,              -- 30 chars
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Dispositivo Terapêutico
CREATE TABLE "TBL_INM_DISPOSITIVO_TERAPEUTICO" (
    "LOCAL_DISPOSITIVO" TEXT,            -- C/F/S
    "TIPO_DISPOSITIVO" TEXT,             -- BIA2, IVA1, MCC2, etc.
    "DT_INICIAL_DISPOSITIVO" DATETIME,
    "DT_FINAL_DISPOSITIVO" DATETIME,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Alta Administrativa
CREATE TABLE "TBL_INM_ALTA_ADMINISTRATIVA" (
    "NR_ATENDIMENTO_ALTA" TEXT,          -- 25 chars
    "NR_AUTORIZACAO_ALTA" TEXT,          -- 25 chars
    "DT_AUTORIZACAO_ALTA" DATETIME,
    "DT_INICIAL_ATENDIMENTO" DATETIME,
    "DT_FINAL_ATENDIMENTO" DATETIME,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Análise Crítica
CREATE TABLE "TBL_INM_ANALISE_CRITICA" (
    "DT_ANALISE" DATETIME,
    "ANALISE_CRITICA" TEXT,              -- 1200 chars
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Causa Externa Permanência
CREATE TABLE "TBL_INM_CAUSA_EXTERNA_PERMANENCIA" (
    "DESCRICAO_CAUSA" TEXT,              -- 250 chars
    "TEMPO_CAUSA" TEXT,                  -- 8 chars
    "DT_INICIAL_CAUSA" DATETIME,
    "DT_FINAL_CAUSA" DATETIME,
    "ORIGEM_CAUSA" TEXT,                 -- A/H/R
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Médico Procedimento
CREATE TABLE "TBL_INM_MEDICO_PROCEDIMENTO" (
    "UF_MEDICO_PROC" TEXT,               -- 2 chars
    "CRM_MEDICO_PROC" TEXT,              -- 20 chars
    "TP_ATUACAO_MEDICO_PROC" TEXT,       -- A/A2/A3/R
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Condição Adquirida Suporte Ventilatório
CREATE TABLE "TBL_INM_COND_ADQ_SUP_VENT" (
    "CD_CID_COND_ADQ_VENT" TEXT,
    "DT_OCORRENCIA_COND_ADQ_VENT" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Condição Adquirida Sonda Vesical
CREATE TABLE "TBL_INM_COND_ADQ_SONDA" (
    "CD_CID_COND_ADQ_SONDA" TEXT,
    "DT_OCORRENCIA_COND_ADQ_SONDA" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de Condição Adquirida Cateter Vascular
CREATE TABLE "TBL_INM_COND_ADQ_CAT_VAS" (
    "CD_CID_COND_ADQ_CAT_VAS" TEXT,
    "DT_OCORRENCIA_COND_ADQ_CAT_VAS" TEXT,
    "CD_DTI_ATENDIMENTO" TEXT,
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Inserir dados de exemplo para teste
INSERT INTO "TBL_INM_ATENDIMENTO" (
    "SITUACAO_INTERNACAO",
    "CARATER_INTERNACAO", 
    "PROCEDENCIA_PACIENTE",
    "LEITO",
    "NR_OPERADORA_FONTE_PAGADORA",
    "NR_REGISTRO",
    "NR_ATENDIMENTO",
    "NR_AUTORIZACAO",
    "DT_INTERNACAO",
    "DT_ALTA",
    "CONDICAO_ALTA",
    "DT_AUTORIZACAO",
    "CD_CID_PRINCIPAL",
    "PACIENTE_INTERNADO_OUTRAS_VEZES",
    "HOSPITAL_INTERNACAO_ANTERIOR",
    "ULTIMA_INTERNACAO_30_DIAS",
    "INTERNACAO_COMPLICACAO_RECAIDA",
    "ACAO",
    "NENHUM_DISPOSITIVO_TERAPEUTICO",
    "NOTA",
    "TIPO_NOTA",
    "DT_NOTA",
    "CD_HOSPITAL",
    "NM_HOSPITAL",
    "CNES_HOSPITAL",
    "PORTE_HOSPITAL",
    "COMPLEXIDADE_HOSPITAL",
    "ESFERA_ADM_HOSPITAL",
    "UF_HOSPITAL",
    "CIDADE_HOSPITAL",
    "TP_LOGRADOURO_HOSPITAL",
    "LOGRADOURO_HOSPITAL",
    "NR_LOGRADOURO_HOSPITAL",
    "COMPLEMENTO_LOGRADOURO_HOSPITAL",
    "BAIRRO_HOSPITAL",
    "CEP_HOSPITAL",
    "DT_NASC_PAC",
    "SEXO_PAC",
    "CPF_PAC",
    "CNS_PAC",
    "RECEM_NASCIDO_PAC",
    "PARTICULAR_PAC",
    "VULNERABILIDADE_SOCIAL_PAC",
    "UF_PAC",
    "CIDADE_PAC",
    "TP_LOGRADOURO_PAC",
    "LOGRADOURO_PAC",
    "NR_LOGRADOURO_PAC",
    "COMPLEMENTO_LOGRADOURO_PAC",
    "BAIRRO_PAC",
    "CEP_PAC",
    "CD_OPERADORA",
    "PLANO_OPERADORA",
    "NR_CARTEIRA",
    "DT_VALIDADE_OPERADORA",
    "TP_SUP_VENT",
    "LOCAL_SUP_VENT",
    "TP_INVASIVO_SUP_VENT",
    "DT_INICIAL_SUP_VENT",
    "DT_FINAL_SUP_VENT",
    "CD_CONDICAO_ADQUIRIDA",
    "DT_OCORRENCIA_SUP",
    "NR_ATEND_ALTA_ADM",
    "NR_AUTORIZACAO_ALTA_ADM",
    "CESARIANA_PARTO_ADEQUADO",
    "MEDICACAO_INDUCAO_PARTO",
    "NR_PARTOS_ANTERIORES",
    -- Campos completos de Parto Adequado
    "ANTECEDENTES_OBSTETRICOS",
    "NUMERO_CESAREAS_ANTERIORES",
    "APRESENTACAO_FETAL_RN1",
    "APRESENTACAO_FETAL_RN2",
    "APRESENTACAO_FETAL_RN3",
    "APRESENTACAO_FETAL_RN4",
    "APRESENTACAO_FETAL_RN5",
    "INICIO_TRABALHO_PARTO",
    "RUPTURA_UTERINA",
    "LACERACAO_PERINEAL",
    "TRANSFUSAO_SANGUINEA",
    "MORTE_MATERNA",
    "MORTE_FETAL_INTRAPARTO",
    "ADMISSAO_MATERNA_UTI",
    "RETORNO_SALA_PARTO",
    "INDICE_SATISFACAO_HOSPITAL",
    "INDICE_SATISFACAO_EQUIPE",
    "HOUVE_CONTATO_PELE",
    "POSICAO_PARTO",
    "USO_OCITOCINA_MISOPROSTOL",
    "PARTURIENTE_ACOMPANHADA",
    "PRESENCA_DOULA",
    "REALIZADA_EPISIOTOMIA",
    "HOUVE_ALEITAMENTO_MATERNO",
    "QUANDO_OCORREU_CLAMPAMENTO",
    "HOUVE_METODOS_ANALGESIA",
    "METODO_ANALGESIA",
    "PERIMETRO_CEFALICO_RN1",
    "PERIMETRO_CEFALICO_RN2",
    "PERIMETRO_CEFALICO_RN3",
    "PERIMETRO_CEFALICO_RN4",
    "PERIMETRO_CEFALICO_RN5",
    "TP_STATUS",
    "DS_ERRO",
    "CD_DTI_ATENDIMENTO"
) VALUES (
    1, -- SITUACAO_INTERNACAO
    1, -- CARATER_INTERNACAO
    '1', -- PROCEDENCIA_PACIENTE
    '101', -- LEITO
    '123456', -- NR_OPERADORA_FONTE_PAGADORA
    'REG001', -- NR_REGISTRO
    12345, -- NR_ATENDIMENTO
    67890, -- NR_AUTORIZACAO
    '2024-01-15 10:30:00', -- DT_INTERNACAO
    '2024-01-20 14:00:00', -- DT_ALTA
    '1', -- CONDICAO_ALTA
    '2024-01-15 09:00:00', -- DT_AUTORIZACAO
    'A41.9', -- CD_CID_PRINCIPAL
    'N', -- PACIENTE_INTERNADO_OUTRAS_VEZES
    'N', -- HOSPITAL_INTERNACAO_ANTERIOR
    'N', -- ULTIMA_INTERNACAO_30_DIAS
    'N', -- INTERNACAO_COMPLICACAO_RECAIDA
    'INTERNACAO', -- ACAO
    'S', -- NENHUM_DISPOSITIVO_TERAPEUTICO
    'Paciente internado para tratamento', -- NOTA
    'OBSERVACAO', -- TIPO_NOTA
    '2024-01-15 10:30:00', -- DT_NOTA
    1, -- CD_HOSPITAL
    'Hospital Teste', -- NM_HOSPITAL
    1234567, -- CNES_HOSPITAL
    3, -- PORTE_HOSPITAL
    2, -- COMPLEXIDADE_HOSPITAL
    1, -- ESFERA_ADM_HOSPITAL
    'SP', -- UF_HOSPITAL
    'São Paulo', -- CIDADE_HOSPITAL
    'RUA', -- TP_LOGRADOURO_HOSPITAL
    'Rua das Flores', -- LOGRADOURO_HOSPITAL
    123, -- NR_LOGRADOURO_HOSPITAL
    'A', -- COMPLEMENTO_LOGRADOURO_HOSPITAL
    'Centro', -- BAIRRO_HOSPITAL
    '01234567', -- CEP_HOSPITAL
    '1980-05-15 00:00:00', -- DT_NASC_PAC
    'M', -- SEXO_PAC
    '12345678901', -- CPF_PAC
    '123456789012345', -- CNS_PAC
    'N', -- RECEM_NASCIDO_PAC
    'N', -- PARTICULAR_PAC
    'N', -- VULNERABILIDADE_SOCIAL_PAC
    'SP', -- UF_PAC
    'São Paulo', -- CIDADE_PAC
    'RUA', -- TP_LOGRADOURO_PAC
    'Rua do Paciente', -- LOGRADOURO_PAC
    '456', -- NR_LOGRADOURO_PAC
    'B', -- COMPLEMENTO_LOGRADOURO_PAC
    'Vila Nova', -- BAIRRO_PAC
    '01234567', -- CEP_PAC
    '123', -- CD_OPERADORA
    'Plano Teste', -- PLANO_OPERADORA
    'CART123', -- NR_CARTEIRA
    '2025-12-31 23:59:59', -- DT_VALIDADE_OPERADORA
    'N', -- TP_SUP_VENT
    'N', -- LOCAL_SUP_VENT
    'N', -- TP_INVASIVO_SUP_VENT
    NULL, -- DT_INICIAL_SUP_VENT
    NULL, -- DT_FINAL_SUP_VENT
    NULL, -- CD_CONDICAO_ADQUIRIDA
    NULL, -- DT_OCORRENCIA_SUP
    NULL, -- NR_ATEND_ALTA_ADM
    NULL, -- NR_AUTORIZACAO_ALTA_ADM
    NULL, -- CESARIANA_PARTO_ADEQUADO
    NULL, -- MEDICACAO_INDUCAO_PARTO
    NULL, -- NR_PARTOS_ANTERIORES
    -- Campos completos de Parto Adequado (valores NULL para exemplo)
    NULL, -- ANTECEDENTES_OBSTETRICOS
    NULL, -- NUMERO_CESAREAS_ANTERIORES
    NULL, -- APRESENTACAO_FETAL_RN1
    NULL, -- APRESENTACAO_FETAL_RN2
    NULL, -- APRESENTACAO_FETAL_RN3
    NULL, -- APRESENTACAO_FETAL_RN4
    NULL, -- APRESENTACAO_FETAL_RN5
    NULL, -- INICIO_TRABALHO_PARTO
    NULL, -- RUPTURA_UTERINA
    NULL, -- LACERACAO_PERINEAL
    NULL, -- TRANSFUSAO_SANGUINEA
    NULL, -- MORTE_MATERNA
    NULL, -- MORTE_FETAL_INTRAPARTO
    NULL, -- ADMISSAO_MATERNA_UTI
    NULL, -- RETORNO_SALA_PARTO
    NULL, -- INDICE_SATISFACAO_HOSPITAL
    NULL, -- INDICE_SATISFACAO_EQUIPE
    NULL, -- HOUVE_CONTATO_PELE
    NULL, -- POSICAO_PARTO
    NULL, -- USO_OCITOCINA_MISOPROSTOL
    NULL, -- PARTURIENTE_ACOMPANHADA
    NULL, -- PRESENCA_DOULA
    NULL, -- REALIZADA_EPISIOTOMIA
    NULL, -- HOUVE_ALEITAMENTO_MATERNO
    NULL, -- QUANDO_OCORREU_CLAMPAMENTO
    NULL, -- HOUVE_METODOS_ANALGESIA
    NULL, -- METODO_ANALGESIA
    NULL, -- PERIMETRO_CEFALICO_RN1
    NULL, -- PERIMETRO_CEFALICO_RN2
    NULL, -- PERIMETRO_CEFALICO_RN3
    NULL, -- PERIMETRO_CEFALICO_RN4
    NULL, -- PERIMETRO_CEFALICO_RN5
    'A', -- TP_STATUS
    NULL, -- DS_ERRO
    'DTI_1' -- CD_DTI_ATENDIMENTO
);

-- Inserir dados de exemplo para médico
INSERT INTO "TBL_INM_MEDICO" (
    "NM_MEDICO",
    "DDD_MEDICO",
    "NR_TELEFONE_MEDICO",
    "EMAIL_MEDICO",
    "UF_MEDICO",
    "CRM_MEDICO",
    "ESPECIALIDADE_MEDICO",
    "MEDICO_RESPONSAVEL",
    "TP_ATUACAO_MEDICO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'Dr. João Silva',
    11, -- DDD_MEDICO
    987654321, -- NR_TELEFONE_MEDICO
    'joao.silva@hospital.com', -- EMAIL_MEDICO
    'SP',
    '123456',
    'Clínica Médica',
    'S', -- MEDICO_RESPONSAVEL
    '1', -- TP_ATUACAO_MEDICO
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para CID secundário
INSERT INTO "TBL_INM_CID_SEC" (
    "CD_CID",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'I10',
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para procedimento
INSERT INTO "TBL_INM_PROCEDIMENTO" (
    "CD_PROCEDIMENTO",
    "DT_EXEC",
    "DT_SOLIC",
    "DT_FIM_EXEC",
    "CD_CIRURGIA_AVISO",
    "CRM_MEDICO_PROCEDIMENTO",
    "UF_MEDICO_PROCEDIMENTO",
    "TP_ATUACAO_MEDICO_PROCEDIMENTO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    '0310010019',
    '2024-01-16 08:00:00',
    '2024-01-16 07:00:00', -- DT_SOLIC
    '2024-01-16 10:00:00', -- DT_FIM_EXEC
    'CIR001', -- CD_CIRURGIA_AVISO
    '123456',
    'SP',
    '1',
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Exemplo de dados de Parto Adequado com valores reais
INSERT INTO "TBL_INM_ATENDIMENTO" (
    "SITUACAO_INTERNACAO",
    "CARATER_INTERNACAO", 
    "PROCEDENCIA_PACIENTE",
    "LEITO",
    "NR_OPERADORA_FONTE_PAGADORA",
    "NR_REGISTRO",
    "NR_ATENDIMENTO",
    "NR_AUTORIZACAO",
    "DT_INTERNACAO",
    "DT_ALTA",
    "CONDICAO_ALTA",
    "DT_AUTORIZACAO",
    "CD_CID_PRINCIPAL",
    "PACIENTE_INTERNADO_OUTRAS_VEZES",
    "HOSPITAL_INTERNACAO_ANTERIOR",
    "ULTIMA_INTERNACAO_30_DIAS",
    "INTERNACAO_COMPLICACAO_RECAIDA",
    "ACAO",
    "NENHUM_DISPOSITIVO_TERAPEUTICO",
    "NOTA",
    "TIPO_NOTA",
    "DT_NOTA",
    "CD_HOSPITAL",
    "NM_HOSPITAL",
    "CNES_HOSPITAL",
    "PORTE_HOSPITAL",
    "COMPLEXIDADE_HOSPITAL",
    "ESFERA_ADM_HOSPITAL",
    "UF_HOSPITAL",
    "CIDADE_HOSPITAL",
    "TP_LOGRADOURO_HOSPITAL",
    "LOGRADOURO_HOSPITAL",
    "NR_LOGRADOURO_HOSPITAL",
    "COMPLEMENTO_LOGRADOURO_HOSPITAL",
    "BAIRRO_HOSPITAL",
    "CEP_HOSPITAL",
    "DT_NASC_PAC",
    "SEXO_PAC",
    "CPF_PAC",
    "CNS_PAC",
    "RECEM_NASCIDO_PAC",
    "PARTICULAR_PAC",
    "VULNERABILIDADE_SOCIAL_PAC",
    "UF_PAC",
    "CIDADE_PAC",
    "TP_LOGRADOURO_PAC",
    "LOGRADOURO_PAC",
    "NR_LOGRADOURO_PAC",
    "COMPLEMENTO_LOGRADOURO_PAC",
    "BAIRRO_PAC",
    "CEP_PAC",
    "CD_OPERADORA",
    "PLANO_OPERADORA",
    "NR_CARTEIRA",
    "DT_VALIDADE_OPERADORA",
    "TP_SUP_VENT",
    "LOCAL_SUP_VENT",
    "TP_INVASIVO_SUP_VENT",
    "DT_INICIAL_SUP_VENT",
    "DT_FINAL_SUP_VENT",
    "CD_CONDICAO_ADQUIRIDA",
    "DT_OCORRENCIA_SUP",
    "NR_ATEND_ALTA_ADM",
    "NR_AUTORIZACAO_ALTA_ADM",
    "CESARIANA_PARTO_ADEQUADO",
    "MEDICACAO_INDUCAO_PARTO",
    "NR_PARTOS_ANTERIORES",
    -- Campos completos de Parto Adequado com dados reais
    "ANTECEDENTES_OBSTETRICOS",
    "NUMERO_CESAREAS_ANTERIORES",
    "APRESENTACAO_FETAL_RN1",
    "APRESENTACAO_FETAL_RN2",
    "APRESENTACAO_FETAL_RN3",
    "APRESENTACAO_FETAL_RN4",
    "APRESENTACAO_FETAL_RN5",
    "INICIO_TRABALHO_PARTO",
    "RUPTURA_UTERINA",
    "LACERACAO_PERINEAL",
    "TRANSFUSAO_SANGUINEA",
    "MORTE_MATERNA",
    "MORTE_FETAL_INTRAPARTO",
    "ADMISSAO_MATERNA_UTI",
    "RETORNO_SALA_PARTO",
    "INDICE_SATISFACAO_HOSPITAL",
    "INDICE_SATISFACAO_EQUIPE",
    "HOUVE_CONTATO_PELE",
    "POSICAO_PARTO",
    "USO_OCITOCINA_MISOPROSTOL",
    "PARTURIENTE_ACOMPANHADA",
    "PRESENCA_DOULA",
    "REALIZADA_EPISIOTOMIA",
    "HOUVE_ALEITAMENTO_MATERNO",
    "QUANDO_OCORREU_CLAMPAMENTO",
    "HOUVE_METODOS_ANALGESIA",
    "METODO_ANALGESIA",
    "PERIMETRO_CEFALICO_RN1",
    "PERIMETRO_CEFALICO_RN2",
    "PERIMETRO_CEFALICO_RN3",
    "PERIMETRO_CEFALICO_RN4",
    "PERIMETRO_CEFALICO_RN5",
    "TP_STATUS",
    "DS_ERRO",
    "CD_DTI_ATENDIMENTO"
) VALUES (
    1, -- SITUACAO_INTERNACAO
    1, -- CARATER_INTERNACAO
    'M', -- PROCEDENCIA_PACIENTE (Comunidade)
    '202', -- LEITO
    '789012', -- NR_OPERADORA_FONTE_PAGADORA
    'REG002', -- NR_REGISTRO
    12346, -- NR_ATENDIMENTO
    67891, -- NR_AUTORIZACAO
    '2024-01-16 08:00:00', -- DT_INTERNACAO
    '2024-01-18 12:00:00', -- DT_ALTA
    'A', -- CONDICAO_ALTA (Casa)
    '2024-01-16 07:30:00', -- DT_AUTORIZACAO
    'O80.1', -- CD_CID_PRINCIPAL (Parto normal)
    'N', -- PACIENTE_INTERNADO_OUTRAS_VEZES
    'N', -- HOSPITAL_INTERNACAO_ANTERIOR
    'N', -- ULTIMA_INTERNACAO_30_DIAS
    'N', -- INTERNACAO_COMPLICACAO_RECAIDA
    'INCLUIR', -- ACAO
    'S', -- NENHUM_DISPOSITIVO_TERAPEUTICO
    'Parto normal sem complicações', -- NOTA
    'A', -- TIPO_NOTA (Admissão)
    '2024-01-16 08:00:00', -- DT_NOTA
    1, -- CD_HOSPITAL
    'Hospital Maternidade', -- NM_HOSPITAL
    1234568, -- CNES_HOSPITAL
    3, -- PORTE_HOSPITAL
    2, -- COMPLEXIDADE_HOSPITAL
    4, -- ESFERA_ADM_HOSPITAL (Privada)
    'SP', -- UF_HOSPITAL
    'São Paulo', -- CIDADE_HOSPITAL
    'RUA', -- TP_LOGRADOURO_HOSPITAL
    'Rua das Maternidades', -- LOGRADOURO_HOSPITAL
    456, -- NR_LOGRADOURO_HOSPITAL
    'B', -- COMPLEMENTO_LOGRADOURO_HOSPITAL
    'Centro', -- BAIRRO_HOSPITAL
    '01234568', -- CEP_HOSPITAL
    '1990-03-20 00:00:00', -- DT_NASC_PAC
    'F', -- SEXO_PAC
    '98765432109', -- CPF_PAC
    '987654321098765', -- CNS_PAC
    'N', -- RECEM_NASCIDO_PAC
    'N', -- PARTICULAR_PAC
    'N', -- VULNERABILIDADE_SOCIAL_PAC
    'SP', -- UF_PAC
    'São Paulo', -- CIDADE_PAC
    'RUA', -- TP_LOGRADOURO_PAC
    'Rua da Paciente', -- LOGRADOURO_PAC
    '789', -- NR_LOGRADOURO_PAC
    'C', -- COMPLEMENTO_LOGRADOURO_PAC
    'Vila Nova', -- BAIRRO_PAC
    '01234568', -- CEP_PAC
    '456', -- CD_OPERADORA
    'Plano Maternidade', -- PLANO_OPERADORA
    'CART456', -- NR_CARTEIRA
    '2025-12-31 23:59:59', -- DT_VALIDADE_OPERADORA
    'N', -- TP_SUP_VENT
    'N', -- LOCAL_SUP_VENT
    'N', -- TP_INVASIVO_SUP_VENT
    NULL, -- DT_INICIAL_SUP_VENT
    NULL, -- DT_FINAL_SUP_VENT
    NULL, -- CD_CONDICAO_ADQUIRIDA
    NULL, -- DT_OCORRENCIA_SUP
    NULL, -- NR_ATEND_ALTA_ADM
    NULL, -- NR_AUTORIZACAO_ALTA_ADM
    'N', -- CESARIANA_PARTO_ADEQUADO (Não foi cesariana)
    'N', -- MEDICACAO_INDUCAO_PARTO
    '0', -- NR_PARTOS_ANTERIORES
    -- Campos completos de Parto Adequado com dados reais
    'NL', -- ANTECEDENTES_OBSTETRICOS (Nulípara)
    '0', -- NUMERO_CESAREAS_ANTERIORES
    'CF', -- APRESENTACAO_FETAL_RN1 (Cefálica)
    NULL, -- APRESENTACAO_FETAL_RN2
    NULL, -- APRESENTACAO_FETAL_RN3
    NULL, -- APRESENTACAO_FETAL_RN4
    NULL, -- APRESENTACAO_FETAL_RN5
    'EP', -- INICIO_TRABALHO_PARTO (Espontâneo)
    'N', -- RUPTURA_UTERINA
    'N', -- LACERACAO_PERINEAL
    'N', -- TRANSFUSAO_SANGUINEA
    'N', -- MORTE_MATERNA
    'N', -- MORTE_FETAL_INTRAPARTO
    'N', -- ADMISSAO_MATERNA_UTI
    'N', -- RETORNO_SALA_PARTO
    '9', -- INDICE_SATISFACAO_HOSPITAL
    '10', -- INDICE_SATISFACAO_EQUIPE
    'S', -- HOUVE_CONTATO_PELE
    '2', -- POSICAO_PARTO (Não Supino)
    '3', -- USO_OCITOCINA_MISOPROSTOL (3º Estágio)
    'S', -- PARTURIENTE_ACOMPANHADA
    'N', -- PRESENCA_DOULA
    'N', -- REALIZADA_EPISIOTOMIA
    'S', -- HOUVE_ALEITAMENTO_MATERNO
    '2', -- QUANDO_OCORREU_CLAMPAMENTO (Até 30 segundos)
    'S', -- HOUVE_METODOS_ANALGESIA
    'Analgesia peridural', -- METODO_ANALGESIA
    '34.5', -- PERIMETRO_CEFALICO_RN1
    NULL, -- PERIMETRO_CEFALICO_RN2
    NULL, -- PERIMETRO_CEFALICO_RN3
    NULL, -- PERIMETRO_CEFALICO_RN4
    NULL, -- PERIMETRO_CEFALICO_RN5
    'A', -- TP_STATUS
    NULL, -- DS_ERRO
    'DTI_2' -- CD_DTI_ATENDIMENTO
);

-- Inserir dados de exemplo para médico do parto
INSERT INTO "TBL_INM_MEDICO" (
    "NM_MEDICO",
    "DDD_MEDICO",
    "NR_TELEFONE_MEDICO",
    "EMAIL_MEDICO",
    "UF_MEDICO",
    "CRM_MEDICO",
    "ESPECIALIDADE_MEDICO",
    "MEDICO_RESPONSAVEL",
    "TP_ATUACAO_MEDICO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'Dra. Maria Santos',
    11, -- DDD_MEDICO
    987654322, -- NR_TELEFONE_MEDICO
    'maria.santos@hospital.com', -- EMAIL_MEDICO
    'SP',
    '654321',
    'Ginecologia e Obstetrícia',
    'S', -- MEDICO_RESPONSAVEL
    '1', -- TP_ATUACAO_MEDICO
    'DTI_2', -- CD_DTI_ATENDIMENTO
    2
);

-- Inserir dados de exemplo para CID secundário do parto
INSERT INTO "TBL_INM_CID_SEC" (
    "CD_CID",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'Z37.0',
    'DTI_2', -- CD_DTI_ATENDIMENTO
    2
);

-- Inserir dados de exemplo para procedimento do parto
INSERT INTO "TBL_INM_PROCEDIMENTO" (
    "CD_PROCEDIMENTO",
    "DT_EXEC",
    "DT_SOLIC",
    "DT_FIM_EXEC",
    "CD_CIRURGIA_AVISO",
    "CRM_MEDICO_PROCEDIMENTO",
    "UF_MEDICO_PROCEDIMENTO",
    "TP_ATUACAO_MEDICO_PROCEDIMENTO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    '0310010020',
    '2024-01-17 10:00:00',
    '2024-01-17 09:30:00', -- DT_SOLIC
    '2024-01-17 11:30:00', -- DT_FIM_EXEC
    'PARTO001', -- CD_CIRURGIA_AVISO
    '654321',
    'SP',
    'R', -- Responsável
    'DTI_2', -- CD_DTI_ATENDIMENTO
    2
);

-- Inserir dados de exemplo para RN (Recém-Nascido)
INSERT INTO "TBL_INM_RN" (
    "PESO_NASCIMENTO",
    "IDADE_GESTACIONAL",
    "COMPRIMENTO",
    "SEXO_RN",
    "NASCIDO_VIVO",
    "TOCOTRAUMATISMO",
    "APGAR",
    "APGAR_QUINTO_MINUTO",
    "ALTA_48_HORAS",
    "NR_AUTORIZACAO_MAE",
    "NR_ATENDIMENTO_MAE",
    "NR_CARTEIRA_MAE",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    3200, -- PESO_NASCIMENTO (gramas)
    '39.0', -- IDADE_GESTACIONAL (semanas)
    '50.5', -- COMPRIMENTO (cm)
    'M', -- SEXO_RN
    'S', -- NASCIDO_VIVO
    'N', -- TOCOTRAUMATISMO
    'S', -- APGAR
    9, -- APGAR_QUINTO_MINUTO
    'S', -- ALTA_48_HORAS
    '67891', -- NR_AUTORIZACAO_MAE
    '12346', -- NR_ATENDIMENTO_MAE
    'CART456', -- NR_CARTEIRA_MAE
    'DTI_2', -- CD_DTI_ATENDIMENTO
    2
);

-- Inserir dados de exemplo para Dispositivo Terapêutico
INSERT INTO "TBL_INM_DISPOSITIVO_TERAPEUTICO" (
    "LOCAL_DISPOSITIVO",
    "TIPO_DISPOSITIVO",
    "DT_INICIAL_DISPOSITIVO",
    "DT_FINAL_DISPOSITIVO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'F', -- LOCAL_DISPOSITIVO (Fora do CTI)
    'MCC2', -- TIPO_DISPOSITIVO (Monitorização cardíaca contínua)
    '2024-01-16 08:30:00', -- DT_INICIAL_DISPOSITIVO
    '2024-01-18 11:30:00', -- DT_FINAL_DISPOSITIVO
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Alta Administrativa
INSERT INTO "TBL_INM_ALTA_ADMINISTRATIVA" (
    "NR_ATENDIMENTO_ALTA",
    "NR_AUTORIZACAO_ALTA",
    "DT_AUTORIZACAO_ALTA",
    "DT_INICIAL_ATENDIMENTO",
    "DT_FINAL_ATENDIMENTO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    '12345', -- NR_ATENDIMENTO_ALTA
    '67890', -- NR_AUTORIZACAO_ALTA
    '2024-01-15 09:00:00', -- DT_AUTORIZACAO_ALTA
    '2024-01-15 10:30:00', -- DT_INICIAL_ATENDIMENTO
    '2024-01-20 14:00:00', -- DT_FINAL_ATENDIMENTO
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Análise Crítica
INSERT INTO "TBL_INM_ANALISE_CRITICA" (
    "DT_ANALISE",
    "ANALISE_CRITICA",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    '2024-01-21 10:00:00', -- DT_ANALISE
    'Paciente apresentou evolução favorável durante a internação. Tratamento adequado conforme protocolo. Alta hospitalar sem complicações.', -- ANALISE_CRITICA
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Causa Externa Permanência
INSERT INTO "TBL_INM_CAUSA_EXTERNA_PERMANENCIA" (
    "DESCRICAO_CAUSA",
    "TEMPO_CAUSA",
    "DT_INICIAL_CAUSA",
    "DT_FINAL_CAUSA",
    "ORIGEM_CAUSA",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'Aguardando liberação de leito em UTI', -- DESCRICAO_CAUSA
    '48:00:00', -- TEMPO_CAUSA
    '2024-01-15 10:30:00', -- DT_INICIAL_CAUSA
    '2024-01-17 10:30:00', -- DT_FINAL_CAUSA
    'H', -- ORIGEM_CAUSA (Hospitalar)
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Médico Procedimento
INSERT INTO "TBL_INM_MEDICO_PROCEDIMENTO" (
    "UF_MEDICO_PROC",
    "CRM_MEDICO_PROC",
    "TP_ATUACAO_MEDICO_PROC",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'SP', -- UF_MEDICO_PROC
    '123456', -- CRM_MEDICO_PROC
    'R', -- TP_ATUACAO_MEDICO_PROC (Responsável)
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Condição Adquirida Suporte Ventilatório
INSERT INTO "TBL_INM_COND_ADQ_SUP_VENT" (
    "CD_CID_COND_ADQ_VENT",
    "DT_OCORRENCIA_COND_ADQ_VENT",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'J96.0', -- CD_CID_COND_ADQ_VENT
    '2024-01-16 08:00:00', -- DT_OCORRENCIA_COND_ADQ_VENT
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Condição Adquirida Sonda Vesical
INSERT INTO "TBL_INM_COND_ADQ_SONDA" (
    "CD_CID_COND_ADQ_SONDA",
    "DT_OCORRENCIA_COND_ADQ_SONDA",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'N39.0', -- CD_CID_COND_ADQ_SONDA
    '2024-01-16 09:00:00', -- DT_OCORRENCIA_COND_ADQ_SONDA
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para Condição Adquirida Cateter Vascular
INSERT INTO "TBL_INM_COND_ADQ_CAT_VAS" (
    "CD_CID_COND_ADQ_CAT_VAS",
    "DT_OCORRENCIA_COND_ADQ_CAT_VAS",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'T81.4', -- CD_CID_COND_ADQ_CAT_VAS
    '2024-01-16 10:00:00', -- DT_OCORRENCIA_COND_ADQ_CAT_VAS
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);
