-- Script para criar as tabelas TBL_INM_* no PostgreSQL
-- Estrutura ATUALIZADA com todas as colunas corrigidas
-- Baseado na estrutura do Oracle e nas referências do código

-- Tabela principal de atendimento
CREATE TABLE "TBL_INM_ATENDIMENTO" (
    "SITUACAO_INTERNACAO" INTEGER,
    "CARATER_INTERNACAO" INTEGER,
    "PROCEDENCIA_PACIENTE" VARCHAR(1),
    "LEITO" VARCHAR(50),
    "NR_OPERADORA_FONTE_PAGADORA" VARCHAR(25),
    "NR_REGISTRO" VARCHAR(25),
    "NR_ATENDIMENTO" INTEGER,
    "NR_AUTORIZACAO" INTEGER,
    "DT_INTERNACAO" TIMESTAMP,
    "DT_ALTA" TIMESTAMP,
    "CONDICAO_ALTA" VARCHAR(1),
    "DT_AUTORIZACAO" TIMESTAMP,
    "CD_CID_PRINCIPAL" VARCHAR(15),
    "PACIENTE_INTERNADO_OUTRAS_VEZES" VARCHAR(1),
    "HOSPITAL_INTERNACAO_ANTERIOR" VARCHAR(1),
    "ULTIMA_INTERNACAO_30_DIAS" VARCHAR(1),
    "INTERNACAO_COMPLICACAO_RECAIDA" VARCHAR(1),
    "ACAO" VARCHAR(15),
    "NENHUM_DISPOSITIVO_TERAPEUTICO" VARCHAR(1),
    "NOTA" TEXT,
    "TIPO_NOTA" VARCHAR(100),
    "DT_NOTA" TIMESTAMP,
    "CD_HOSPITAL" INTEGER,
    "NM_HOSPITAL" VARCHAR(120),
    "CNES_HOSPITAL" INTEGER,
    "PORTE_HOSPITAL" INTEGER,
    "COMPLEXIDADE_HOSPITAL" INTEGER,
    "ESFERA_ADM_HOSPITAL" INTEGER,
    "UF_HOSPITAL" VARCHAR(2),
    "CIDADE_HOSPITAL" VARCHAR(100),
    "TP_LOGRADOURO_HOSPITAL" VARCHAR(20),
    "LOGRADOURO_HOSPITAL" VARCHAR(72),
    "NR_LOGRADOURO_HOSPITAL" INTEGER,
    "COMPLEMENTO_LOGRADOURO_HOSPITAL" VARCHAR(5),
    "BAIRRO_HOSPITAL" VARCHAR(72),
    "CEP_HOSPITAL" VARCHAR(8),
    "DT_NASC_PAC" TIMESTAMP,
    "SEXO_PAC" VARCHAR(1),
    "CPF_PAC" VARCHAR(11),
    "CNS_PAC" VARCHAR(15),
    "RECEM_NASCIDO_PAC" VARCHAR(1),
    "PARTICULAR_PAC" VARCHAR(1),
    "VULNERABILIDADE_SOCIAL_PAC" VARCHAR(1),
    "UF_PAC" VARCHAR(2),
    "CIDADE_PAC" VARCHAR(100),
    "TP_LOGRADOURO_PAC" VARCHAR(20),
    "LOGRADOURO_PAC" VARCHAR(72),
    "NR_LOGRADOURO_PAC" VARCHAR(8),
    "COMPLEMENTO_LOGRADOURO_PAC" VARCHAR(5),
    "BAIRRO_PAC" VARCHAR(72),
    "CEP_PAC" VARCHAR(8),
    "CD_OPERADORA" VARCHAR(10),
    "PLANO_OPERADORA" VARCHAR(40),
    "NR_CARTEIRA" VARCHAR(30),
    "DT_VALIDADE_OPERADORA" TIMESTAMP,
    "TP_SUP_VENT" VARCHAR(1),
    "LOCAL_SUP_VENT" VARCHAR(1),
    "TP_INVASIVO_SUP_VENT" VARCHAR(1),
    "DT_INICIAL_SUP_VENT" TIMESTAMP,
    "DT_FINAL_SUP_VENT" VARCHAR(20),
    "CD_CONDICAO_ADQUIRIDA" VARCHAR(15),
    "DT_OCORRENCIA_SUP" VARCHAR(20),
    "NR_ATEND_ALTA_ADM" VARCHAR(25),
    "NR_AUTORIZACAO_ALTA_ADM" VARCHAR(25),
    "CESARIANA_PARTO_ADEQUADO" VARCHAR(1),
    "MEDICACAO_INDUCAO_PARTO" VARCHAR(1),
    "NR_PARTOS_ANTERIORES" VARCHAR(10),
    "TP_STATUS" VARCHAR(100),
    "CD_ESTABELECIMENTO" VARCHAR(10),
    "DS_ERRO" VARCHAR(500),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" SERIAL PRIMARY KEY
);

-- Tabela de médicos
CREATE TABLE "TBL_INM_MEDICO" (
    "NM_MEDICO" VARCHAR(300),
    "DDD_MEDICO" INTEGER, -- ADICIONADA
    "NR_TELEFONE_MEDICO" INTEGER, -- ADICIONADA
    "EMAIL_MEDICO" VARCHAR(600), -- ADICIONADA
    "UF_MEDICO" VARCHAR(2),
    "CRM_MEDICO" VARCHAR(20),
    "ESPECIALIDADE_MEDICO" VARCHAR(120),
    "MEDICO_RESPONSAVEL" VARCHAR(1), -- ADICIONADA
    "TP_ATUACAO_MEDICO" VARCHAR(1), -- ADICIONADA
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de CID secundário
CREATE TABLE "TBL_INM_CID_SEC" (
    "CD_CID" VARCHAR(15),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de procedimentos
CREATE TABLE "TBL_INM_PROCEDIMENTO" (
    "CD_PROCEDIMENTO" VARCHAR(20),
    "DT_EXEC" TIMESTAMP,
    "DT_SOLIC" TIMESTAMP, -- ADICIONADA
    "DT_FIM_EXEC" TIMESTAMP, -- ADICIONADA
    "CD_CIRURGIA_AVISO" VARCHAR(50), -- ADICIONADA
    "CRM_MEDICO_PROCEDIMENTO" VARCHAR(20),
    "UF_MEDICO_PROCEDIMENTO" VARCHAR(2),
    "TP_ATUACAO_MEDICO_PROCEDIMENTO" VARCHAR(2),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de CTI
CREATE TABLE "TBL_INM_CTI" (
    "LEITO_CTI" VARCHAR(50),
    "DT_INICIAL_CTI" TIMESTAMP,
    "DT_FINAL_CTI" TIMESTAMP,
    "CD_CID_PRINCIPAL" VARCHAR(15),
    "CONDICAO_ALTA_CTI" VARCHAR(1),
    "UF_CTI" VARCHAR(2),
    "CRM_CTI" VARCHAR(20),
    "CD_HOSPITAL" VARCHAR(10),
    "NM_HOSPITAL" VARCHAR(120),
    "DS_LEITO" VARCHAR(100), -- ADICIONADA
    "TIPO" VARCHAR(50), -- ADICIONADA
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de suporte ventilatório
CREATE TABLE "TBL_INM_SUPORTEVENTILATORIO" (
    "TP_SUP_VENT" VARCHAR(1),
    "LOCAL_SUP_VENT" VARCHAR(1),
    "TP_INVASIVO_SUP_VENT" VARCHAR(1),
    "DT_INICIAL_SUP_VENT" TIMESTAMP,
    "DT_FINAL_SUP_VENT" VARCHAR(20),
    "DT_INICIAL_SUP_VENTILATORIO" TIMESTAMP, -- ADICIONADA
    "DT_FINAL_SUP_VENTILATORIO" TIMESTAMP, -- ADICIONADA
    "CD_CID_COND_ADQ_VENT" VARCHAR(15),
    "DT_COND_ADQ_VENT" VARCHAR(20),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de cateter vascular central
CREATE TABLE "TBL_INM_CATETERVASCULARCENTRAL" (
    "LOCAL_CAT_VAS" VARCHAR(1),
    "DT_INICIO_CAT_VAS" VARCHAR(20),
    "DT_FIM_CAT_VAS" VARCHAR(20),
    "CD_CID_CAT_VAS" VARCHAR(15),
    "DT_CAT_VAS" VARCHAR(20),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de sonda vesical de demora
CREATE TABLE "TBL_INM_SONDAVESICALDEDEMORA" (
    "LOCAL_SON_VES" VARCHAR(1),
    "DT_INICIO_SON_VES" VARCHAR(20),
    "DT_FIM_SON_VES" VARCHAR(20),
    "CD_CID_COND_ADQ_SONDA" VARCHAR(15),
    "DT_COND_ADQ_SONDA" VARCHAR(20),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Tabela de condição adquirida
CREATE TABLE "TBL_INM_COND_ADQ" (
    "CD_CID_COND_ADQ" VARCHAR(15),
    "DT_OCORRENCIA_COND_ADQ" VARCHAR(20),
    "DT_MANIFESTACAO_COND_ADQ" VARCHAR(20),
    "UF_MED_COND_ADQ" VARCHAR(2),
    "CRM_MED_COND_ADQ" VARCHAR(20),
    "CD_DTI_ATENDIMENTO" VARCHAR(50), -- ADICIONADA
    "ID_ATENDIMENTO" INTEGER,
    FOREIGN KEY ("ID_ATENDIMENTO") REFERENCES "TBL_INM_ATENDIMENTO"("ID_ATENDIMENTO")
);

-- Inserir alguns dados de exemplo para teste
INSERT INTO "TBL_INM_ATENDIMENTO" (
    "SITUACAO_INTERNACAO",
    "CARATER_INTERNACAO", 
    "PROCEDENCIA_PACIENTE",
    "LEITO",
    "NR_OPERADORA_FONTE_PAGADORA",
    "NR_REGISTRO",
    "NR_ATENDIMENTO",
    "NR_AUTORIZACAO",
    "DT_INTERNACAO",
    "DT_ALTA",
    "CONDICAO_ALTA",
    "DT_AUTORIZACAO",
    "CD_CID_PRINCIPAL",
    "PACIENTE_INTERNADO_OUTRAS_VEZES",
    "HOSPITAL_INTERNACAO_ANTERIOR",
    "ULTIMA_INTERNACAO_30_DIAS",
    "INTERNACAO_COMPLICACAO_RECAIDA",
    "ACAO",
    "NENHUM_DISPOSITIVO_TERAPEUTICO",
    "NOTA",
    "TIPO_NOTA",
    "DT_NOTA",
    "CD_HOSPITAL",
    "NM_HOSPITAL",
    "CNES_HOSPITAL",
    "PORTE_HOSPITAL",
    "COMPLEXIDADE_HOSPITAL",
    "ESFERA_ADM_HOSPITAL",
    "UF_HOSPITAL",
    "CIDADE_HOSPITAL",
    "TP_LOGRADOURO_HOSPITAL",
    "LOGRADOURO_HOSPITAL",
    "NR_LOGRADOURO_HOSPITAL",
    "COMPLEMENTO_LOGRADOURO_HOSPITAL",
    "BAIRRO_HOSPITAL",
    "CEP_HOSPITAL",
    "DT_NASC_PAC",
    "SEXO_PAC",
    "CPF_PAC",
    "CNS_PAC",
    "RECEM_NASCIDO_PAC",
    "PARTICULAR_PAC",
    "VULNERABILIDADE_SOCIAL_PAC",
    "UF_PAC",
    "CIDADE_PAC",
    "TP_LOGRADOURO_PAC",
    "LOGRADOURO_PAC",
    "NR_LOGRADOURO_PAC",
    "COMPLEMENTO_LOGRADOURO_PAC",
    "BAIRRO_PAC",
    "CEP_PAC",
    "CD_OPERADORA",
    "PLANO_OPERADORA",
    "NR_CARTEIRA",
    "DT_VALIDADE_OPERADORA",
    "TP_SUP_VENT",
    "LOCAL_SUP_VENT",
    "TP_INVASIVO_SUP_VENT",
    "DT_INICIAL_SUP_VENT",
    "DT_FINAL_SUP_VENT",
    "CD_CONDICAO_ADQUIRIDA",
    "DT_OCORRENCIA_SUP",
    "NR_ATEND_ALTA_ADM",
    "NR_AUTORIZACAO_ALTA_ADM",
    "CESARIANA_PARTO_ADEQUADO",
    "MEDICACAO_INDUCAO_PARTO",
    "NR_PARTOS_ANTERIORES",
    "TP_STATUS",
    "DS_ERRO",
    "CD_DTI_ATENDIMENTO"
) VALUES (
    1, -- SITUACAO_INTERNACAO
    1, -- CARATER_INTERNACAO
    '1', -- PROCEDENCIA_PACIENTE
    '101', -- LEITO
    '123456', -- NR_OPERADORA_FONTE_PAGADORA
    'REG001', -- NR_REGISTRO
    12345, -- NR_ATENDIMENTO
    67890, -- NR_AUTORIZACAO
    '2024-01-15 10:30:00', -- DT_INTERNACAO
    '2024-01-20 14:00:00', -- DT_ALTA
    '1', -- CONDICAO_ALTA
    '2024-01-15 09:00:00', -- DT_AUTORIZACAO
    'A41.9', -- CD_CID_PRINCIPAL
    'N', -- PACIENTE_INTERNADO_OUTRAS_VEZES
    'N', -- HOSPITAL_INTERNACAO_ANTERIOR
    'N', -- ULTIMA_INTERNACAO_30_DIAS
    'N', -- INTERNACAO_COMPLICACAO_RECAIDA
    'INTERNACAO', -- ACAO
    'S', -- NENHUM_DISPOSITIVO_TERAPEUTICO
    'Paciente internado para tratamento', -- NOTA
    'OBSERVACAO', -- TIPO_NOTA
    '2024-01-15 10:30:00', -- DT_NOTA
    1, -- CD_HOSPITAL
    'Hospital Teste', -- NM_HOSPITAL
    1234567, -- CNES_HOSPITAL
    3, -- PORTE_HOSPITAL
    2, -- COMPLEXIDADE_HOSPITAL
    1, -- ESFERA_ADM_HOSPITAL
    'SP', -- UF_HOSPITAL
    'São Paulo', -- CIDADE_HOSPITAL
    'RUA', -- TP_LOGRADOURO_HOSPITAL
    'Rua das Flores', -- LOGRADOURO_HOSPITAL
    123, -- NR_LOGRADOURO_HOSPITAL
    'A', -- COMPLEMENTO_LOGRADOURO_HOSPITAL
    'Centro', -- BAIRRO_HOSPITAL
    '01234567', -- CEP_HOSPITAL
    '1980-05-15 00:00:00', -- DT_NASC_PAC
    'M', -- SEXO_PAC
    '12345678901', -- CPF_PAC
    '123456789012345', -- CNS_PAC
    'N', -- RECEM_NASCIDO_PAC
    'N', -- PARTICULAR_PAC
    'N', -- VULNERABILIDADE_SOCIAL_PAC
    'SP', -- UF_PAC
    'São Paulo', -- CIDADE_PAC
    'RUA', -- TP_LOGRADOURO_PAC
    'Rua do Paciente', -- LOGRADOURO_PAC
    '456', -- NR_LOGRADOURO_PAC
    'B', -- COMPLEMENTO_LOGRADOURO_PAC
    'Vila Nova', -- BAIRRO_PAC
    '01234567', -- CEP_PAC
    '123', -- CD_OPERADORA
    'Plano Teste', -- PLANO_OPERADORA
    'CART123', -- NR_CARTEIRA
    '2025-12-31 23:59:59', -- DT_VALIDADE_OPERADORA
    'N', -- TP_SUP_VENT
    'N', -- LOCAL_SUP_VENT
    'N', -- TP_INVASIVO_SUP_VENT
    NULL, -- DT_INICIAL_SUP_VENT
    NULL, -- DT_FINAL_SUP_VENT
    NULL, -- CD_CONDICAO_ADQUIRIDA
    NULL, -- DT_OCORRENCIA_SUP
    NULL, -- NR_ATEND_ALTA_ADM
    NULL, -- NR_AUTORIZACAO_ALTA_ADM
    NULL, -- CESARIANA_PARTO_ADEQUADO
    NULL, -- MEDICACAO_INDUCAO_PARTO
    NULL, -- NR_PARTOS_ANTERIORES
    'A', -- TP_STATUS
    NULL, -- DS_ERRO
    'DTI_1' -- CD_DTI_ATENDIMENTO
);

-- Inserir dados de exemplo para médico
INSERT INTO "TBL_INM_MEDICO" (
    "NM_MEDICO",
    "DDD_MEDICO",
    "NR_TELEFONE_MEDICO",
    "EMAIL_MEDICO",
    "UF_MEDICO",
    "CRM_MEDICO",
    "ESPECIALIDADE_MEDICO",
    "MEDICO_RESPONSAVEL",
    "TP_ATUACAO_MEDICO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'Dr. João Silva',
    11, -- DDD_MEDICO
    987654321, -- NR_TELEFONE_MEDICO
    'joao.silva@hospital.com', -- EMAIL_MEDICO
    'SP',
    '123456',
    'Clínica Médica',
    'S', -- MEDICO_RESPONSAVEL
    '1', -- TP_ATUACAO_MEDICO
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para CID secundário
INSERT INTO "TBL_INM_CID_SEC" (
    "CD_CID",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    'I10',
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

-- Inserir dados de exemplo para procedimento
INSERT INTO "TBL_INM_PROCEDIMENTO" (
    "CD_PROCEDIMENTO",
    "DT_EXEC",
    "DT_SOLIC",
    "DT_FIM_EXEC",
    "CD_CIRURGIA_AVISO",
    "CRM_MEDICO_PROCEDIMENTO",
    "UF_MEDICO_PROCEDIMENTO",
    "TP_ATUACAO_MEDICO_PROCEDIMENTO",
    "CD_DTI_ATENDIMENTO",
    "ID_ATENDIMENTO"
) VALUES (
    '0310010019',
    '2024-01-16 08:00:00',
    '2024-01-16 07:00:00', -- DT_SOLIC
    '2024-01-16 10:00:00', -- DT_FIM_EXEC
    'CIR001', -- CD_CIRURGIA_AVISO
    '123456',
    'SP',
    '1',
    'DTI_1', -- CD_DTI_ATENDIMENTO
    1
);

COMMIT;
